export interface Project {
  id: string;
  name: string;
  category: "Diseño Interior" | "Arquitectura";
  year: string;
  location: string;
  description: string;
  image: string;
  gallery: string[];
  alt: string;
}

const WP = "https://estudiomodocasa.com/wp-content/uploads";

export const projects: Project[] = [
  {
    id: "hudson",
    name: "Hudson",
    category: "Arquitectura",
    year: "2024",
    location: "Buenos Aires",
    description: "Residencia contemporánea que integra materiales naturales con una paleta neutra que potencia la luz. Cada espacio fue diseñado para generar amplitud sin perder calidez.",
    image: `${WP}/2022/12/hudson_2025_01-1024x683.jpg`,
    gallery: [`${WP}/2022/12/hudson_2025_01.jpg`, `${WP}/2022/12/hudson_2025_02.jpg`, `${WP}/2022/12/hudson_2025_03.jpg`, `${WP}/2022/12/hudson_2025_04.jpg`],
    alt: "Hudson, Arquitectura residencial",
  },
  {
    id: "palacio-estrugamou",
    name: "Palacio Estrugamou",
    category: "Diseño Interior",
    year: "2025",
    location: "Buenos Aires",
    description: "Intervención de interiorismo en un edificio patrimonial emblemático. El trabajo respeta la arquitectura original mientras introduce materiales y mobiliario contemporáneos que conviven con moldurajes y techos históricos.",
    image: `${WP}/2025/06/Estrugamou-06-1024x683.jpg`,
    gallery: [`${WP}/2025/06/Estrugamou-01.jpg`, `${WP}/2025/06/Estrugamou-02.jpg`, `${WP}/2025/06/Estrugamou-03.jpg`, `${WP}/2025/06/Estrugamou-04.jpg`],
    alt: "Palacio Estrugamou, Diseño interior patrimonial",
  },
  {
    id: "casa-terravista",
    name: "Casa Terravista",
    category: "Arquitectura",
    year: "2022",
    location: "Buenos Aires",
    description: "Proyecto de arquitectura residencial que dialoga con el paisaje. Planos horizontales enmarcan las vistas y generan terrazas habitables. Los materiales naturales y grandes paños vidriados disuelven el límite entre interior y exterior.",
    image: `${WP}/2022/12/terravista-1-1024x727.jpg`,
    gallery: [`${WP}/2022/12/terravista-1.jpg`, `${WP}/2022/12/terravista-2.jpg`, `${WP}/2022/12/terravista-3.jpg`, `${WP}/2022/12/terravista-4.jpg`],
    alt: "Casa Terravista, Arquitectura residencial",
  },
  {
    id: "nordelta-barrio-el-golf",
    name: "Nordelta, Barrio El Golf",
    category: "Diseño Interior",
    year: "2025",
    location: "Nordelta, Buenos Aires",
    description: "Diseño integral de una residencia en country de alta gama. El proyecto abarca desde la distribución de ambientes hasta la selección de materiales y el diseño de mobiliario a medida.",
    image: `${WP}/2025/06/1.1-1024x683.jpg`,
    gallery: [`${WP}/2025/06/1.1.jpg`, `${WP}/2025/06/2.2.jpg`, `${WP}/2025/06/3.3.jpg`, `${WP}/2025/06/4.4.jpg`],
    alt: "Nordelta Barrio El Golf, Diseño interior residencial",
  },
  {
    id: "cervino",
    name: "Cerviño",
    category: "Diseño Interior",
    year: "2025",
    location: "Palermo, Buenos Aires",
    description: "Departamento de planta abierta que prioriza la integración entre ambientes. El diseño maximiza la luz natural con tonos neutros y textiles de alta calidad que definen el carácter del proyecto.",
    image: `${WP}/2025/06/image-1-1024x683.jpg`,
    gallery: [`${WP}/2025/06/image-1.jpg`, `${WP}/2025/06/image-2.jpg`, `${WP}/2025/06/image-3.jpg`, `${WP}/2025/06/image-4-scaled.jpg`],
    alt: "Cerviño, Diseño interior contemporáneo",
  },
  {
    id: "donna-acqua",
    name: "Donna Acqua",
    category: "Diseño Interior",
    year: "2025",
    location: "Caballito, Buenos Aires",
    description: "Intervención de interiorismo moderno en el edificio Donna Acqua. Materiales seleccionados, iluminación a medida y mobiliario que equilibra funcionalidad y estética.",
    image: `${WP}/2025/06/donaaqua_01-1024x683.jpg`,
    gallery: [`${WP}/2025/06/donaaqua_01.jpg`, `${WP}/2025/06/donaaqua_02.jpg`, `${WP}/2025/06/donaaqua_03.jpg`, `${WP}/2025/06/donaaqua_04.jpg`],
    alt: "Donna Acqua, Diseño interior moderno",
  },
  {
    id: "salguero-torre-gelly",
    name: "Salguero Torre Gelly",
    category: "Diseño Interior",
    year: "2025",
    location: "Buenos Aires",
    description: "Unidad residencial de alta gama en tower boutique. El proyecto apuesta por una paleta monocromática cálida, superficies de mármol y carpintería personalizada que define cada ambiente.",
    image: `${WP}/2025/06/salguerotg-01-1024x683.jpg`,
    gallery: [`${WP}/2025/06/salguerotg-01.jpg`, `${WP}/2025/06/salguerotg-02.jpg`, `${WP}/2025/06/salguerotg-03.jpg`, `${WP}/2025/06/salguerotg-04.jpg`],
    alt: "Salguero Torre Gelly, Diseño interior premium",
  },
  {
    id: "sls",
    name: "SLS",
    category: "Diseño Interior",
    year: "2023",
    location: "Buenos Aires",
    description: "Proyecto de interiorismo en edificio residencial de lujo. Espacios diáfanos con materiales de primera calidad, terminaciones en mármol y una iluminación diseñada para cada momento del día.",
    image: `${WP}/2023/09/SLS-ESTUDIO1-1.jpg`,
    gallery: [`${WP}/2023/09/sls-v2-001.jpg`, `${WP}/2023/09/sls-v2-002.jpg`, `${WP}/2023/09/sls-v2-003.jpg`, `${WP}/2023/09/sls-v2-004.jpg`],
    alt: "SLS, Diseño interior de lujo",
  },
  {
    id: "devoto",
    name: "Devoto",
    category: "Diseño Interior",
    year: "2023",
    location: "Devoto, Buenos Aires",
    description: "Residencia familiar en barrio residencial. El diseño reinterpreta la casa tradicional con una estética contemporánea que respeta la escala del entorno y optimiza cada rincón del espacio.",
    image: `${WP}/2023/09/devoto_v2-4055.jpg`,
    gallery: [`${WP}/2023/09/devoto_v2-4055.jpg`, `${WP}/2023/09/devoto_v2-4076.jpg`, `${WP}/2023/09/devoto_v2-4086.jpg`, `${WP}/2023/09/devoto_v2-4099.jpg`],
    alt: "Devoto, Diseño interior contemporáneo",
  },
  {
    id: "saint-thomas",
    name: "Saint Thomas",
    category: "Diseño Interior",
    year: "2023",
    location: "Buenos Aires",
    description: "Proyecto bespoke de interiorismo para una residencia de lujo. Cada elemento fue diseñado a medida: carpintería, tapizados, iluminación y selección de obras de arte integradas al espacio.",
    image: `${WP}/2023/09/stthomas_01-1024x576.jpg`,
    gallery: [`${WP}/2023/09/stthomas_01.jpg`, `${WP}/2023/09/stthomas_03.jpg`, `${WP}/2023/09/stthomas_07.jpg`, `${WP}/2023/09/stthomas_08.jpg`],
    alt: "Saint Thomas, Diseño interior bespoke",
  },
  {
    id: "unkanny",
    name: "Unkanny",
    category: "Diseño Interior",
    year: "2023",
    location: "Buenos Aires",
    description: "Intervención de interiorismo con un marcado carácter editorial. La propuesta juega con contrastes de escala, materiales inesperados y una paleta que oscila entre el blanco roto y el negro profundo.",
    image: `${WP}/2023/09/unkanny_v2-001.jpg`,
    gallery: [`${WP}/2023/09/unkanny_v2-001.jpg`, `${WP}/2023/09/unkanny_v2-003.jpg`, `${WP}/2023/09/unkanny_v2-004.jpg`, `${WP}/2023/09/unkanny_v2-005.jpg`],
    alt: "Unkanny, Diseño interior editorial",
  },
  {
    id: "chaco",
    name: "Chaco",
    category: "Diseño Interior",
    year: "2023",
    location: "Buenos Aires",
    description: "Residencia de lujo con una estética que dialoga con la arquitectura federal. Materiales nobles, maderas cálidas y una paleta que equilibra la tradición con la contemporaneidad.",
    image: `${WP}/2023/09/chaco_v2-001.jpg`,
    gallery: [`${WP}/2023/09/chaco_v2-001.jpg`, `${WP}/2023/09/chaco_v2-002.jpg`, `${WP}/2023/09/chaco_v2-003b.jpg`, `${WP}/2023/09/chaco_v2-004b.jpg`],
    alt: "Chaco, Diseño interior residencial de lujo",
  },
  {
    id: "cramer",
    name: "Cramer",
    category: "Diseño Interior",
    year: "2023",
    location: "Buenos Aires",
    description: "Departamento en edificio contemporáneo. La propuesta de interiorismo apuesta por la planta libre, la integración de ambientes y una carpintería personalizada que organiza y define cada sector.",
    image: `${WP}/2023/04/2-Copiar-1024x682.jpg`,
    gallery: [`${WP}/2023/04/1-Copiar.jpg`, `${WP}/2023/04/2-Copiar.jpg`, `${WP}/2023/04/3-Copiar.jpg`, `${WP}/2023/04/4-Copiar.jpg`],
    alt: "Cramer, Diseño interior contemporáneo",
  },
  {
    id: "arcos-belgrano",
    name: "Arcos Belgrano",
    category: "Diseño Interior",
    year: "2023",
    location: "Belgrano, Buenos Aires",
    description: "Unidad residencial en uno de los edificios más reconocidos del barrio. El proyecto integra materiales de primera línea con una distribución que maximiza las vistas y la luz natural.",
    image: `${WP}/2023/04/ARCOS-BELGRANO-1-Copiar-1024x688.jpg`,
    gallery: [`${WP}/2023/04/ARCOS-BELGRANO-1-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-2-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-3-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-4-Copiar.jpg`],
    alt: "Arcos Belgrano, Diseño interior residencial",
  },
  {
    id: "aleph",
    name: "Aleph",
    category: "Arquitectura",
    year: "2023",
    location: "Buenos Aires",
    description: "Proyecto de arquitectura de autor con una mirada internacional. La obra combina una volumetría depurada con interiores de alta gama, resultado de la colaboración entre arquitectura e interiorismo.",
    image: `${WP}/2023/04/ALEPH-7-Copiar-1024x683.jpg`,
    gallery: [`${WP}/2023/04/ALEPH-1-Copiar.jpg`, `${WP}/2023/04/ALEPH-2-Copiar.jpg`, `${WP}/2023/04/ALEPH-3-Copiar.jpg`, `${WP}/2023/04/ALEPH-7-Copiar.jpg`],
    alt: "Aleph, Arquitectura de autor",
  },
  {
    id: "sls-puerto-madero",
    name: "SLS Puerto Madero",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, Buenos Aires",
    description: "Penthouse en el icónico edificio SLS de Puerto Madero. Diseño cosmopolita que combina materialidad de lujo con vistas panorámicas al río. Fotografía de Federico Kulekdjian.",
    image: `${WP}/2021/08/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-19-1.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-04.jpg`],
    alt: "SLS Puerto Madero, Penthouse cosmopolita",
  },
  {
    id: "vicente-lopez-iii-al-rio",
    name: "Vicente López III, Al Río",
    category: "Diseño Interior",
    year: "2021",
    location: "Vicente López, Buenos Aires",
    description: "Residencia frente al río con una propuesta de interiorismo que prioriza las vistas y la relación con el exterior. Materiales naturales y paleta neutra que acompañan el paisaje ribereño.",
    image: `${WP}/2021/09/MAX_8719.jpg`,
    gallery: [`${WP}/2021/10/MAX_1496.jpg`, `${WP}/2021/10/MAX_1523.jpg`, `${WP}/2021/10/MAX_8558.jpg`, `${WP}/2021/10/MAX_8619.jpg`],
    alt: "Vicente López III Al Río, Diseño interior ribereño",
  },
  {
    id: "puerto-madero-v-alvear-tower",
    name: "Puerto Madero V, Alvear Tower",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, Buenos Aires",
    description: "Unidad en la icónica Alvear Tower de Puerto Madero. Diseño de autor que integra materialidad premium con una propuesta espacial que maximiza las vistas a la ciudad y al río.",
    image: `${WP}/2021/07/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-25-1024x683.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-04.jpg`],
    alt: "Puerto Madero Alvear Tower, Diseño de autor",
  },
  {
    id: "vicente-lopez-ii-al-rio",
    name: "Vicente López II, Al Río",
    category: "Diseño Interior",
    year: "2021",
    location: "Vicente López, Buenos Aires",
    description: "Segunda intervención en Vicente López con una visión contemporánea que valora la relación interior-exterior. Espacios integrados con vista al río y materiales que evocan la naturaleza.",
    image: `${WP}/2021/07/6-1024x683.jpg`,
    gallery: [`${WP}/2021/10/1-1.jpg`, `${WP}/2021/10/2-1.jpg`, `${WP}/2021/10/5-1.jpg`, `${WP}/2021/10/6-1.jpg`],
    alt: "Vicente López II Al Río, Diseño interior contemporáneo",
  },
  {
    id: "obra-goyena-caballito",
    name: "Obra Goyena, Caballito",
    category: "Diseño Interior",
    year: "2021",
    location: "Caballito, Buenos Aires",
    description: "Residencia de lujo en un barrio con fuerte identidad. El proyecto transforma un departamento en un espacio singular, con materiales nobles y detalles de carpintería que elevan cada ambiente.",
    image: `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-11.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-04.jpg`],
    alt: "Obra Goyena Caballito, Diseño interior de lujo",
  },
  {
    id: "godoy-cruz-torres-deco",
    name: "Godoy Cruz, Torres Deco",
    category: "Diseño Interior",
    year: "2021",
    location: "Buenos Aires",
    description: "Unidad en complejo residencial de diseño. La propuesta integra un lenguaje contemporáneo con referencias clásicas, generando ambientes sofisticados y funcionales para la vida cotidiana.",
    image: `${WP}/2021/08/P2A3616.jpg`,
    gallery: [`${WP}/2021/10/P2A3616.jpg`, `${WP}/2021/10/P2A3627.jpg`, `${WP}/2021/10/P2A3631.jpg`, `${WP}/2021/10/P2A3663-luces.jpg`],
    alt: "Godoy Cruz Torres Deco, Diseño interior",
  },
  {
    id: "segui-torre-renoir",
    name: "Seguí, Torre Renoir",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, Buenos Aires",
    description: "Piso en la Torre Renoir de Puerto Madero. Diseño de autor que combina lujo y funcionalidad en un espacio de gran superficie, con vistas privilegiadas y materialidad de primera línea.",
    image: `${WP}/2021/10/P2A5568.jpg`,
    gallery: [`${WP}/2021/10/P2A5524.jpg`, `${WP}/2021/10/P2A5533.jpg`, `${WP}/2021/10/P2A5544.jpg`, `${WP}/2021/10/P2A5568.jpg`],
    alt: "Seguí Torre Renoir, Diseño interior de lujo",
  },
  {
    id: "juana-manso-los-molinos",
    name: "Juana Manso, Los Molinos",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, Buenos Aires",
    description: "Intervención de reciclaje patrimonial en un edificio histórico de Puerto Madero. El proyecto preserva la esencia arquitectónica original mientras introduce un interiorismo contemporáneo de alta gama.",
    image: `${WP}/2021/07/MAX_9468-1024x683.jpg`,
    gallery: [`${WP}/2021/10/MAX_9468.jpg`, `${WP}/2021/10/MAX_9482.jpg`, `${WP}/2021/10/MAX_9641.jpg`, `${WP}/2021/10/MAX_9648.jpg`],
    alt: "Juana Manso Los Molinos, Reciclaje patrimonial",
  },
  {
    id: "belgrano-ii-mirabilia",
    name: "Belgrano II, Mirabilia",
    category: "Diseño Interior",
    year: "2022",
    location: "Belgrano, Buenos Aires",
    description: "Residencia de lujo en Belgrano con una propuesta de interiorismo que equilibra la escala del edificio con la intimidad del hogar. Materialidad premium y carpintería a medida en cada ambiente.",
    image: `${WP}/2021/08/P2A6980-WEB.jpg`,
    gallery: [`${WP}/2022/12/Bano-2-WEB.jpg`, `${WP}/2022/12/Bano-WEB.jpg`, `${WP}/2022/12/Biblioteca-WEB.jpg`, `${WP}/2022/12/Escritorio-2-WEB.jpg`],
    alt: "Belgrano II Mirabilia, Diseño interior de lujo",
  },
  {
    id: "country-abril-casa-country",
    name: "Country Abril, Casa Country",
    category: "Diseño Interior",
    year: "2021",
    location: "Buenos Aires",
    description: "Casa en country con un programa que integra vida familiar y entretenimiento. El diseño propone ambientes amplios, conexión con el jardín y una materialidad natural que dialoga con el entorno verde.",
    image: `${WP}/2021/10/2.jpg`,
    gallery: [`${WP}/2021/10/1.jpg`, `${WP}/2021/10/2.jpg`, `${WP}/2021/10/3.jpg`, `${WP}/2021/10/4.jpg`],
    alt: "Country Abril Casa Country, Diseño interior",
  },
  {
    id: "casa-de-verano-pinamar",
    name: "Casa de Verano, Villa de Mar, Pinamar",
    category: "Diseño Interior",
    year: "2021",
    location: "Pinamar, Buenos Aires",
    description: "Casa de verano en la costa atlántica. El diseño captura la esencia relajada de la vida en la playa con materiales resistentes al clima marino, colores neutros y espacios que invitan al descanso.",
    image: `${WP}/2021/10/2-IMG_1483-1024x682.jpg`,
    gallery: [`${WP}/2021/10/1-estar-correjido.jpg`, `${WP}/2021/10/01aIMG_1866.jpg`, `${WP}/2021/10/2-IMG_1483.jpg`, `${WP}/2021/10/3-IMG_1488.jpg`],
    alt: "Casa de Verano Pinamar, Diseño interior costero",
  },
  {
    id: "palermo-le-parc-alcorta",
    name: "Palermo, Le Parc Alcorta",
    category: "Diseño Interior",
    year: "2021",
    location: "Palermo, Buenos Aires",
    description: "Residencia en el exclusivo complejo Le Parc Alcorta. Diseño de autor que aprovecha los metros y las alturas del edificio para crear ambientes de doble altura con vistas al parque.",
    image: `${WP}/2021/08/DSC_2869.jpg`,
    gallery: [`${WP}/2021/10/DSC_2821.jpg`, `${WP}/2021/10/DSC_2831.jpg`, `${WP}/2021/10/DSC_2844.jpg`, `${WP}/2021/10/DSC_2866.jpg`],
    alt: "Palermo Le Parc Alcorta, Diseño interior de autor",
  },
  {
    id: "puerto-madero-ii-zencity",
    name: "Puerto Madero II, Zencity",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, Buenos Aires",
    description: "Unidad en Zencity, el complejo de uso mixto más grande de Latinoamérica. La propuesta de interiorismo contemporáneo aprovecha la escala del edificio para crear un hogar sofisticado con vistas al río.",
    image: `${WP}/2021/08/MAI2863_1.jpg`,
    gallery: [`${WP}/2021/10/MAI2624-copy.jpg`, `${WP}/2021/10/MAI2626.jpg`, `${WP}/2021/10/MAI2630.jpg`, `${WP}/2021/10/MAI2634.jpg`],
    alt: "Puerto Madero II Zencity, Diseño interior contemporáneo",
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export const categories = ["Todos", "Diseño Interior", "Arquitectura"] as const;
export type Category = (typeof categories)[number];
