/**
 * Tipo de pieza (obra terminada / en desarrollo / render / real estate).
 * Estructura lista para cuando el estudio sume renders/real estate.
 */
export type ProjectType = "Obra" | "En desarrollo" | "Render" | "Real estate";

export interface Project {
  id: string;
  name: string;
  category: "Diseño Interior" | "Arquitectura";
  type?: ProjectType;
  year: string;
  /** Barrio/zona corto, para las cards de la grilla */
  location: string;
  /** Dirección completa (ficha técnica + JSON-LD) */
  locationFull: string;
  status: string;
  /** Alcance / servicios prestados */
  services: string;
  /** Memoria técnica: materialidades y resolución (dato real del estudio) */
  memoriaTecnica: string;
  /** Memoria descriptiva: relato del proyecto (dato real del estudio) */
  memoriaDescriptiva: string;
  /** Palabras clave SEO/IA */
  keywords: string[];
  /** Texto intro del detalle (= memoria descriptiva) */
  description: string;
  image: string;
  gallery: string[];
  alt: string;
}

const WP = "https://estudiomodocasa.com/wp-content/uploads";

/**
 * Contenido real de cada obra provisto por el estudio (Fran / Vir, 09/2026).
 * Las fotos siguen saliendo del WordPress; migrarlas a hosting propio queda
 * pendiente. Obras del listado sin fotos en nuestro set (Torre Link,
 * Vicente López al Río I) todavía no se cargan.
 */
export const projects: Project[] = [
  {
    id: "hudson",
    name: "Hudson",
    category: "Arquitectura",
    year: "2021",
    location: "Guillermo Hudson, PBA",
    locationFull: "Barrio Privado Magallanes, Guillermo Hudson, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Revestimiento en piedra natural grafito, cielorraso de hormigón visto y mobiliario en madera maciza ennegrecida.",
    memoriaDescriptiva: "Una casa de líneas crudas donde el hormigón dialoga con la piedra tallada por el tiempo. Materialidad honesta para una vida en contacto con la naturaleza.",
    keywords: ["casa de campo minimalista Barrio Hudson", "arquitectura contemporánea Buenos Aires", "casa en country PBA"],
    description: "Una casa de líneas crudas donde el hormigón dialoga con la piedra tallada por el tiempo. Materialidad honesta para una vida en contacto con la naturaleza.",
    image: `${WP}/2022/12/hudson_2025_01-1024x683.jpg`,
    gallery: [`${WP}/2022/12/hudson_2025_01.jpg`, `${WP}/2022/12/hudson_2025_02.jpg`, `${WP}/2022/12/hudson_2025_03.jpg`, `${WP}/2022/12/hudson_2025_04.jpg`],
    alt: "Hudson, casa de campo minimalista en Barrio Hudson",
  },
  {
    id: "palacio-estrugamou",
    name: "Palacio Estrugamou",
    category: "Diseño Interior",
    year: "2023",
    location: "Retiro, CABA",
    locationFull: "Palacio Estrugamou, Esmeralda 1319, Retiro, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Parquet espina de pescado Indusparquet, biblioteca en hierro negro y sillones de cuero cognac.",
    memoriaDescriptiva: "En un palacio de 1929, el pasado se conserva y el presente se instala con delicadeza. Cada detalle histórico convive con una mirada actual.",
    keywords: ["departamento de lujo Retiro", "edificio histórico Buenos Aires", "interiorismo departamentos premium CABA"],
    description: "En un palacio de 1929, el pasado se conserva y el presente se instala con delicadeza. Cada detalle histórico convive con una mirada actual.",
    image: `${WP}/2025/06/Estrugamou-06-1024x683.jpg`,
    gallery: [`${WP}/2025/06/Estrugamou-01.jpg`, `${WP}/2025/06/Estrugamou-02.jpg`, `${WP}/2025/06/Estrugamou-03.jpg`, `${WP}/2025/06/Estrugamou-04.jpg`],
    alt: "Palacio Estrugamou, interiorismo en edificio histórico de Retiro",
  },
  {
    id: "casa-terravista",
    name: "Casa Terravista",
    category: "Arquitectura",
    year: "2023",
    location: "General Rodríguez, PBA",
    locationFull: "Barrio Privado Terravista, General Rodríguez, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Piso de hormigón alisado, mesas ratona en mármol Calello y paneles de nogal retroiluminados.",
    memoriaDescriptiva: "La madera y el hormigón se encuentran en equilibrio justo. Una casa donde lo cálido y lo sobrio conviven sin levantar la voz.",
    keywords: ["casa moderna General Rodríguez", "arquitectura contemporánea Buenos Aires", "interiorismo residencial premium"],
    description: "La madera y el hormigón se encuentran en equilibrio justo. Una casa donde lo cálido y lo sobrio conviven sin levantar la voz.",
    image: `${WP}/2022/12/terravista-1-1024x727.jpg`,
    gallery: [`${WP}/2022/12/terravista-1.jpg`, `${WP}/2022/12/terravista-2.jpg`, `${WP}/2022/12/terravista-3.jpg`, `${WP}/2022/12/terravista-4.jpg`],
    alt: "Casa Terravista, arquitectura contemporánea en General Rodríguez",
  },
  {
    id: "nordelta-barrio-el-golf",
    name: "Nordelta, Barrio El Golf",
    category: "Arquitectura",
    year: "2025",
    location: "Nordelta, PBA",
    locationFull: "Barrio El Golf, Nordelta, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto",
    memoriaTecnica: "Chimenea en piedra natural de Mármoles Calello, piso técnico en porcelanato claro y carpintería de nogal.",
    memoriaDescriptiva: "Una casa que se abre al verde de Nordelta, donde el fuego y la madera construyen calidez. El paisaje entra sin pedir permiso.",
    keywords: ["casa de lujo Nordelta", "arquitectura residencial Barrio El Golf", "diseño interior casas de campo"],
    description: "Una casa que se abre al verde de Nordelta, donde el fuego y la madera construyen calidez. El paisaje entra sin pedir permiso.",
    image: `${WP}/2025/06/1.1-1024x683.jpg`,
    gallery: [`${WP}/2025/06/1.1.jpg`, `${WP}/2025/06/2.2.jpg`, `${WP}/2025/06/3.3.jpg`, `${WP}/2025/06/4.4.jpg`],
    alt: "Nordelta Barrio El Golf, casa de lujo",
  },
  {
    id: "cervino",
    name: "Cerviño",
    category: "Diseño Interior",
    year: "2022",
    location: "Palermo, CABA",
    locationFull: "Cerviño, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Columnas en madera de nogal, isla de cocina Johnson en piedra oscura y piso Patagonia Flooring.",
    memoriaDescriptiva: "Un recorrido de madera que organiza el espacio como un ritmo pausado. La casa se despliega entre columnas cálidas y luz cenital.",
    keywords: ["departamento premium Barrio Norte", "diseño interior Buenos Aires", "arquitectura residencial CABA"],
    description: "Un recorrido de madera que organiza el espacio como un ritmo pausado. La casa se despliega entre columnas cálidas y luz cenital.",
    image: `${WP}/2025/06/image-1-1024x683.jpg`,
    gallery: [`${WP}/2025/06/image-1.jpg`, `${WP}/2025/06/image-2.jpg`, `${WP}/2025/06/image-3.jpg`, `${WP}/2025/06/image-4-scaled.jpg`],
    alt: "Cerviño, diseño interior contemporáneo",
  },
  {
    id: "donna-acqua",
    name: "Donna Acqua",
    category: "Diseño Interior",
    year: "2023",
    location: "Caballito, CABA",
    locationFull: "Edificio Donna Acqua, Avenida Juan Bautista Alberdi 1823, Caballito, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mueble bajo en madera con nichos retroiluminados, piso de porcelanato claro y sofás en boucle hueso.",
    memoriaDescriptiva: "En Caballito, un living horizontal y sereno donde la luz indirecta dibuja el espacio. Calidez contenida, elegancia sin ruido.",
    keywords: ["departamento premium Caballito", "torre residencial Buenos Aires", "diseño interior departamentos CABA"],
    description: "En Caballito, un living horizontal y sereno donde la luz indirecta dibuja el espacio. Calidez contenida, elegancia sin ruido.",
    image: `${WP}/2025/06/donaaqua_01-1024x683.jpg`,
    gallery: [`${WP}/2025/06/donaaqua_01.jpg`, `${WP}/2025/06/donaaqua_02.jpg`, `${WP}/2025/06/donaaqua_03.jpg`, `${WP}/2025/06/donaaqua_04.jpg`],
    alt: "Donna Acqua, diseño interior en Caballito",
  },
  {
    id: "salguero-torre-gelly",
    name: "Torre Gelly",
    category: "Diseño Interior",
    year: "2024",
    location: "Palermo Chico, CABA",
    locationFull: "Gelly 3368, Palermo Chico, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Piso de madera clara Indusparquet, mueble de TV en laca blanca y mesa de comedor en mármol.",
    memoriaDescriptiva: "En Palermo Chico, la luz de la tarde recorre superficies claras y texturas cálidas. Un living que abraza la vida cotidiana con la serenidad de lo esencial.",
    keywords: ["departamento premium Palermo Chico", "torre residencial Buenos Aires", "diseño interior contemporáneo"],
    description: "En Palermo Chico, la luz de la tarde recorre superficies claras y texturas cálidas. Un living que abraza la vida cotidiana con la serenidad de lo esencial.",
    image: `${WP}/2025/06/salguerotg-01-1024x683.jpg`,
    gallery: [`${WP}/2025/06/salguerotg-01.jpg`, `${WP}/2025/06/salguerotg-02.jpg`, `${WP}/2025/06/salguerotg-03.jpg`, `${WP}/2025/06/salguerotg-04.jpg`],
    alt: "Torre Gelly, diseño interior en Palermo Chico",
  },
  {
    id: "sls",
    name: "SLS",
    category: "Diseño Interior",
    year: "2020",
    location: "Puerto Madero, CABA",
    locationFull: "Torre SLS Puerto Madero, Juana Manso 1725, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Piso de mármol Calacatta de Mármoles Calello, separadores en madera ennegrecida y sofá en terciopelo gris.",
    memoriaDescriptiva: "Sobre Puerto Madero, el mármol se despliega como un lienzo y la ciudad se asoma detrás del vidrio. Sofisticación con vista al río.",
    keywords: ["torre SLS Puerto Madero", "departamento de lujo Buenos Aires", "residencias premium con vista al río"],
    description: "Sobre Puerto Madero, el mármol se despliega como un lienzo y la ciudad se asoma detrás del vidrio. Sofisticación con vista al río.",
    image: `${WP}/2023/09/SLS-ESTUDIO1-1.jpg`,
    gallery: [`${WP}/2023/09/sls-v2-001.jpg`, `${WP}/2023/09/sls-v2-002.jpg`, `${WP}/2023/09/sls-v2-003.jpg`, `${WP}/2023/09/sls-v2-004.jpg`],
    alt: "SLS Puerto Madero, departamento de lujo con vista al río",
  },
  {
    id: "devoto",
    name: "Devoto",
    category: "Diseño Interior",
    year: "2021",
    location: "Villa Devoto, CABA",
    locationFull: "Devoto, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Columnas de hormigón visto, piso de porcelanato claro y mobiliario en acero Johnson.",
    memoriaDescriptiva: "Una casa que se abre por completo al jardín, donde el hormigón y el vidrio dejan pasar la vida. Luz natural como protagonista absoluta.",
    keywords: ["casa moderna Villa Devoto", "arquitectura contemporánea CABA", "interiorismo residencial Buenos Aires"],
    description: "Una casa que se abre por completo al jardín, donde el hormigón y el vidrio dejan pasar la vida. Luz natural como protagonista absoluta.",
    image: `${WP}/2023/09/devoto_v2-4055.jpg`,
    gallery: [`${WP}/2023/09/devoto_v2-4055.jpg`, `${WP}/2023/09/devoto_v2-4076.jpg`, `${WP}/2023/09/devoto_v2-4086.jpg`, `${WP}/2023/09/devoto_v2-4099.jpg`],
    alt: "Devoto, casa moderna en Villa Devoto",
  },
  {
    id: "saint-thomas",
    name: "Saint Thomas",
    category: "Arquitectura",
    year: "2022",
    location: "Canning, PBA",
    locationFull: "Club de Campo Saint Thomas, Canning, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto",
    memoriaTecnica: "Escalera en piedra Calello, estantería en madera de nogal y muros en microcemento gris.",
    memoriaDescriptiva: "En Saint Thomas, la casa se despliega en niveles conectados por la luz. Cada tramo es una pausa entre la piedra y la madera.",
    keywords: ["casa club de campo Canning", "arquitectura contemporánea PBA", "casas de lujo countries Buenos Aires"],
    description: "En Saint Thomas, la casa se despliega en niveles conectados por la luz. Cada tramo es una pausa entre la piedra y la madera.",
    image: `${WP}/2023/09/stthomas_01-1024x576.jpg`,
    gallery: [`${WP}/2023/09/stthomas_01.jpg`, `${WP}/2023/09/stthomas_03.jpg`, `${WP}/2023/09/stthomas_07.jpg`, `${WP}/2023/09/stthomas_08.jpg`],
    alt: "Saint Thomas, casa en club de campo Canning",
  },
  {
    id: "unkanny",
    name: "Unkanny",
    category: "Diseño Interior",
    year: "2025",
    location: "Mar del Plata, PBA",
    locationFull: "Unkanny Tower, Leandro N. Alem 2400, Mar del Plata, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto",
    memoriaTecnica: "Panel de cabecera tapizado, muros con textura símil lino y mesa de luz en madera y piedra.",
    memoriaDescriptiva: "Un dormitorio que abraza en tonos neutros, pensado para el descanso absoluto. La calidez de la tela y la luz tenue como refugio.",
    keywords: ["torre residencial Mar del Plata", "departamentos premium costa atlántica", "diseño de dormitorios de autor"],
    description: "Un dormitorio que abraza en tonos neutros, pensado para el descanso absoluto. La calidez de la tela y la luz tenue como refugio.",
    image: `${WP}/2023/09/unkanny_v2-001.jpg`,
    gallery: [`${WP}/2023/09/unkanny_v2-001.jpg`, `${WP}/2023/09/unkanny_v2-003.jpg`, `${WP}/2023/09/unkanny_v2-004.jpg`, `${WP}/2023/09/unkanny_v2-005.jpg`],
    alt: "Unkanny, dormitorio de autor en Mar del Plata",
  },
  {
    id: "chaco",
    name: "Chaco",
    category: "Diseño Interior",
    year: "2022",
    location: "Resistencia, Chaco",
    locationFull: "Resistencia, Chaco, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto",
    memoriaTecnica: "Muros en microcemento gris, nicho en madera con luz integrada y piso de porcelanato claro.",
    memoriaDescriptiva: "Un proyecto de líneas depuradas, donde cada nicho y quiebre de nivel construye un recorrido íntimo. Minimalismo con carácter.",
    keywords: ["departamento contemporáneo Buenos Aires", "diseño interior minimalista", "arquitectura residencial moderna"],
    description: "Un proyecto de líneas depuradas, donde cada nicho y quiebre de nivel construye un recorrido íntimo. Minimalismo con carácter.",
    image: `${WP}/2023/09/chaco_v2-001.jpg`,
    gallery: [`${WP}/2023/09/chaco_v2-001.jpg`, `${WP}/2023/09/chaco_v2-002.jpg`, `${WP}/2023/09/chaco_v2-003b.jpg`, `${WP}/2023/09/chaco_v2-004b.jpg`],
    alt: "Chaco, diseño interior minimalista en Resistencia",
  },
  {
    id: "cramer",
    name: "Cramer",
    category: "Diseño Interior",
    year: "2021",
    location: "Belgrano, CABA",
    locationFull: "Cramer, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mesa de comedor en madera maciza, piso Indusparquet en tablones y mueble bajo lacado con espejo.",
    memoriaDescriptiva: "En Belgrano, la madera oscura enmarca un comedor de encuentro. Luz cálida y materialidad noble para la vida en comunidad.",
    keywords: ["departamento premium Belgrano", "diseño interior Buenos Aires", "comedores de diseño CABA"],
    description: "En Belgrano, la madera oscura enmarca un comedor de encuentro. Luz cálida y materialidad noble para la vida en comunidad.",
    image: `${WP}/2023/04/2-Copiar-1024x682.jpg`,
    gallery: [`${WP}/2023/04/1-Copiar.jpg`, `${WP}/2023/04/2-Copiar.jpg`, `${WP}/2023/04/3-Copiar.jpg`, `${WP}/2023/04/4-Copiar.jpg`],
    alt: "Cramer, diseño interior en Belgrano",
  },
  {
    id: "arcos-belgrano",
    name: "Arcos Belgrano",
    category: "Diseño Interior",
    year: "2021",
    location: "Belgrano, CABA",
    locationFull: "DOME Torre Arcos, Arcos 1883, Belgrano, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Biblioteca en laca blanca, piso Patagonia Flooring y mesas ratona en mármol Calello.",
    memoriaDescriptiva: "En la Torre DOME, la biblioteca se convierte en protagonista y organiza la vida del living. Orden y calidez en equilibrio.",
    keywords: ["torre DOME Belgrano", "departamento de lujo Buenos Aires", "torres residenciales premium CABA"],
    description: "En la Torre DOME, la biblioteca se convierte en protagonista y organiza la vida del living. Orden y calidez en equilibrio.",
    image: `${WP}/2023/04/ARCOS-BELGRANO-1-Copiar-1024x688.jpg`,
    gallery: [`${WP}/2023/04/ARCOS-BELGRANO-1-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-2-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-3-Copiar.jpg`, `${WP}/2023/04/ARCOS-BELGRANO-4-Copiar.jpg`],
    alt: "Arcos Belgrano, departamento en Torre DOME",
  },
  {
    id: "aleph",
    name: "Aleph",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, CABA",
    locationFull: "Aleph Residences, Petrona Eyle 355, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Panel de TV en mármol Calacatta Calello y madera de nogal, con cielorraso de hormigón visto.",
    memoriaDescriptiva: "En Aleph Residences, el mármol enmarca una biblioteca que narra objetos e historias. Puerto Madero visto desde la calidez de la madera.",
    keywords: ["Aleph Residences Puerto Madero", "departamento de lujo Buenos Aires", "torres residenciales premium CABA"],
    description: "En Aleph Residences, el mármol enmarca una biblioteca que narra objetos e historias. Puerto Madero visto desde la calidez de la madera.",
    image: `${WP}/2023/04/ALEPH-7-Copiar-1024x683.jpg`,
    gallery: [`${WP}/2023/04/ALEPH-1-Copiar.jpg`, `${WP}/2023/04/ALEPH-2-Copiar.jpg`, `${WP}/2023/04/ALEPH-3-Copiar.jpg`, `${WP}/2023/04/ALEPH-7-Copiar.jpg`],
    alt: "Aleph Residences, departamento de lujo en Puerto Madero",
  },
  {
    id: "sls-puerto-madero",
    name: "SLS Puerto Madero",
    category: "Diseño Interior",
    year: "2023",
    location: "Puerto Madero, CABA",
    locationFull: "Torre SLS Puerto Madero, Juana Manso 1725, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Cocina Johnson en madera gris ceniza, isla en piedra Calello y piso de porcelanato claro.",
    memoriaDescriptiva: "La cocina se abre al living y al río en un mismo gesto. Puerto Madero se cuela por cada ventana como parte del diseño.",
    keywords: ["torre SLS Puerto Madero", "departamentos con vista al río Buenos Aires", "cocinas integradas de diseño"],
    description: "La cocina se abre al living y al río en un mismo gesto. Puerto Madero se cuela por cada ventana como parte del diseño.",
    image: `${WP}/2021/08/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-19-1.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-SLS-PUERTO-MADERO-PH_FEDERICO_KULEKDJIAN-04.jpg`],
    alt: "SLS Puerto Madero, cocina integrada con vista al río",
  },
  {
    id: "vicente-lopez-ii-al-rio",
    name: "Vicente López al Río II",
    category: "Diseño Interior",
    year: "2023",
    location: "Vicente López, PBA",
    locationFull: "Complejo Al Río, Avenida del Libertador 101, Vicente López, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mesa de comedor en mármol Calello con base de acero, piso Indusparquet y luminarias colgantes.",
    memoriaDescriptiva: "Una mesa larga para encuentros extensos, enmarcada por el río como telón de fondo. El mármol y la madera dialogan en calma.",
    keywords: ["departamento premium Vicente López", "comedores de diseño Buenos Aires", "departamentos con vista al río PBA"],
    description: "Una mesa larga para encuentros extensos, enmarcada por el río como telón de fondo. El mármol y la madera dialogan en calma.",
    image: `${WP}/2021/07/6-1024x683.jpg`,
    gallery: [`${WP}/2021/10/1-1.jpg`, `${WP}/2021/10/2-1.jpg`, `${WP}/2021/10/5-1.jpg`, `${WP}/2021/10/6-1.jpg`],
    alt: "Vicente López al Río II, comedor con vista al río",
  },
  {
    id: "vicente-lopez-iii-al-rio",
    name: "Vicente López al Río III",
    category: "Diseño Interior",
    year: "2023",
    location: "Vicente López, PBA",
    locationFull: "Complejo Al Río, Avenida del Libertador 101, Vicente López, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Biblioteca en madera retroiluminada, sofá en terciopelo gris y mesa ratona en laca blanca.",
    memoriaDescriptiva: "La luz cálida de la biblioteca acompaña las tardes frente al parque. Un living que invita a quedarse.",
    keywords: ["departamento premium Vicente López", "Complejo Al Río", "departamentos con vista al parque Buenos Aires"],
    description: "La luz cálida de la biblioteca acompaña las tardes frente al parque. Un living que invita a quedarse.",
    // Alojada localmente: la original de WP fallaba de forma intermitente en el optimizador de Next
    image: `/projects/vicente-lopez-iii.jpg`,
    gallery: [`${WP}/2021/10/MAX_1496.jpg`, `${WP}/2021/10/MAX_1523.jpg`, `${WP}/2021/10/MAX_8558.jpg`, `${WP}/2021/10/MAX_8619.jpg`],
    alt: "Vicente López al Río III, living con biblioteca frente al parque",
  },
  {
    id: "puerto-madero-v-alvear-tower",
    name: "Puerto Madero V, Alvear Tower",
    category: "Diseño Interior",
    year: "2019",
    location: "Puerto Madero, CABA",
    locationFull: "Alvear Tower, Boulevard Azucena Villaflor 559, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Piedra natural veteada de Mármoles Calello, biblioteca en madera oscura y piso de mármol pulido.",
    memoriaDescriptiva: "En Alvear Tower, la piedra se convierte en protagonista absoluta. Sofisticación de escala monumental sobre Puerto Madero.",
    keywords: ["Alvear Tower Puerto Madero", "departamento de lujo Buenos Aires", "torres residenciales premium CABA"],
    description: "En Alvear Tower, la piedra se convierte en protagonista absoluta. Sofisticación de escala monumental sobre Puerto Madero.",
    image: `${WP}/2021/07/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-25-1024x683.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-ALVEAR-TOWER-PISO-12-PH-FEDERICO-KULEKDJIAN-04.jpg`],
    alt: "Puerto Madero, Alvear Tower, departamento de lujo",
  },
  {
    id: "obra-goyena-caballito",
    name: "Obra Goyena, Caballito",
    category: "Diseño Interior",
    year: "2021",
    location: "Caballito, CABA",
    locationFull: "Caballito, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mesa de comedor en mármol Calello, piso Indusparquet y lámparas colgantes en cono negro.",
    memoriaDescriptiva: "En Caballito, el mármol y la madera construyen un comedor de carácter. La luz cae en cascada desde lámparas suspendidas.",
    keywords: ["casa moderna Caballito", "arquitectura residencial Buenos Aires", "comedores de diseño CABA"],
    description: "En Caballito, el mármol y la madera construyen un comedor de carácter. La luz cae en cascada desde lámparas suspendidas.",
    image: `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-11.jpg`,
    gallery: [`${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-01.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-02.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-03.jpg`, `${WP}/2021/10/MODO-CASA-PEDRO-GOYENA-PH_FEDERICO_KULEKDJIAN-04.jpg`],
    alt: "Obra Goyena, comedor de diseño en Caballito",
  },
  {
    id: "godoy-cruz-torres-deco",
    name: "Godoy Cruz, Torres Decó",
    category: "Diseño Interior",
    year: "2022",
    location: "Palermo Nuevo, CABA",
    locationFull: "Torres Decó, J. M. Seguí 4600, Palermo Nuevo, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Sofás en boucle gris, sillón en terciopelo mostaza y piso de madera Indusparquet.",
    memoriaDescriptiva: "Un living luminoso donde el color mostaza aporta carácter a la neutralidad. Palermo se filtra por ventanales que no terminan nunca.",
    keywords: ["Torres Decó Palermo", "departamento premium Buenos Aires", "diseño interior contemporáneo CABA"],
    description: "Un living luminoso donde el color mostaza aporta carácter a la neutralidad. Palermo se filtra por ventanales que no terminan nunca.",
    image: `${WP}/2021/08/P2A3616.jpg`,
    gallery: [`${WP}/2021/10/P2A3616.jpg`, `${WP}/2021/10/P2A3627.jpg`, `${WP}/2021/10/P2A3631.jpg`, `${WP}/2021/10/P2A3663-luces.jpg`],
    alt: "Godoy Cruz, Torres Decó, living en Palermo Nuevo",
  },
  {
    id: "segui-torre-renoir",
    name: "Seguí, Torre Renoir",
    category: "Diseño Interior",
    year: "2022",
    location: "Puerto Madero, CABA",
    locationFull: "Torres Renoir, Marta Lynch 485, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Panel de TV en piedra Calello, piso Patagonia Flooring y puffs en boucle color hueso.",
    memoriaDescriptiva: "En Torres Renoir, la piedra enmarca el fuego y el río se despliega como cuadro permanente. Calma de altura sobre Puerto Madero.",
    keywords: ["Torres Renoir Puerto Madero", "departamento premium Buenos Aires", "departamentos con vista al río CABA"],
    description: "En Torres Renoir, la piedra enmarca el fuego y el río se despliega como cuadro permanente. Calma de altura sobre Puerto Madero.",
    image: `${WP}/2021/10/P2A5568.jpg`,
    gallery: [`${WP}/2021/10/P2A5524.jpg`, `${WP}/2021/10/P2A5533.jpg`, `${WP}/2021/10/P2A5544.jpg`, `${WP}/2021/10/P2A5568.jpg`],
    alt: "Seguí, Torre Renoir, departamento con vista al río",
  },
  {
    id: "juana-manso-los-molinos",
    name: "Juana Manso, Los Molinos",
    category: "Diseño Interior",
    year: "2021",
    location: "Puerto Madero, CABA",
    locationFull: "Los Molinos, Juana Manso 1100, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mesa de comedor en mármol Calacatta Calello, biblioteca retroiluminada y piso Patagonia Flooring.",
    memoriaDescriptiva: "En Puerto Madero, el comedor se vuelve escenario. Mármol, luz escultórica y madera oscura narran una misma historia de sofisticación.",
    keywords: ["Los Molinos Puerto Madero", "departamento de lujo Buenos Aires", "comedores de diseño premium CABA"],
    description: "En Puerto Madero, el comedor se vuelve escenario. Mármol, luz escultórica y madera oscura narran una misma historia de sofisticación.",
    image: `${WP}/2021/07/MAX_9468-1024x683.jpg`,
    gallery: [`${WP}/2021/10/MAX_9468.jpg`, `${WP}/2021/10/MAX_9482.jpg`, `${WP}/2021/10/MAX_9641.jpg`, `${WP}/2021/10/MAX_9648.jpg`],
    alt: "Juana Manso, Los Molinos, comedor de diseño en Puerto Madero",
  },
  {
    id: "belgrano-ii-mirabilia",
    name: "Belgrano II, Mirabilia",
    category: "Diseño Interior",
    year: "2021",
    location: "Belgrano, CABA",
    locationFull: "Torre Mirabilia Belgrano, Arcos 2646, Belgrano, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Sofá modular en boucle gris, cielorraso técnico con riel de luz y mesas en madera clara.",
    memoriaDescriptiva: "En Torre Mirabilia, la sobriedad se vuelve carácter. Un living curado como una galería íntima y personal.",
    keywords: ["Torre Mirabilia Belgrano", "departamento premium Buenos Aires", "torres residenciales CABA"],
    description: "En Torre Mirabilia, la sobriedad se vuelve carácter. Un living curado como una galería íntima y personal.",
    image: `${WP}/2021/08/P2A6980-WEB.jpg`,
    gallery: [`${WP}/2022/12/Bano-2-WEB.jpg`, `${WP}/2022/12/Bano-WEB.jpg`, `${WP}/2022/12/Biblioteca-WEB.jpg`, `${WP}/2022/12/Escritorio-2-WEB.jpg`],
    alt: "Belgrano II, Torre Mirabilia, living curado",
  },
  {
    id: "country-abril-casa-country",
    name: "Casa Country Abril",
    category: "Diseño Interior",
    year: "2023",
    location: "Guillermo Hudson, PBA",
    locationFull: "Abril Club de Campo, Autopista Buenos Aires - La Plata Km 33.5, Guillermo Hudson, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Mueble bar en madera con detalles espejados, piso de mármol Calello e iluminación indirecta perimetral.",
    memoriaDescriptiva: "Una casa de countries donde el espejo multiplica la luz y los objetos cuentan historias propias. Elegancia clásica renovada.",
    keywords: ["casa de campo Abril Club de Campo", "arquitectura residencial Buenos Aires", "casas en countries PBA"],
    description: "Una casa de countries donde el espejo multiplica la luz y los objetos cuentan historias propias. Elegancia clásica renovada.",
    // Alojada localmente: la original de WP fallaba de forma intermitente en el optimizador de Next
    image: `/projects/country-abril.jpg`,
    gallery: [`${WP}/2021/10/1.jpg`, `${WP}/2021/10/2.jpg`, `${WP}/2021/10/3.jpg`, `${WP}/2021/10/4.jpg`],
    alt: "Casa Country Abril, casa en Abril Club de Campo",
  },
  {
    id: "palermo-le-parc-alcorta",
    name: "Palermo, Le Parc Alcorta",
    category: "Diseño Interior",
    year: "2022",
    location: "Palermo, CABA",
    locationFull: "Le Parc Figueroa Alcorta, Avenida Pres. Figueroa Alcorta 3535, Palermo, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Biblioteca en madera de nogal con nichos en laca azul y piso Indusparquet.",
    memoriaDescriptiva: "Una biblioteca que organiza la vida del living y guarda objetos con carácter propio. Palermo en clave íntima y curada.",
    keywords: ["departamento premium Palermo", "Le Parc Figueroa Alcorta", "diseño interior Buenos Aires"],
    description: "Una biblioteca que organiza la vida del living y guarda objetos con carácter propio. Palermo en clave íntima y curada.",
    image: `${WP}/2021/08/DSC_2869.jpg`,
    gallery: [`${WP}/2021/10/DSC_2821.jpg`, `${WP}/2021/10/DSC_2831.jpg`, `${WP}/2021/10/DSC_2844.jpg`, `${WP}/2021/10/DSC_2866.jpg`],
    alt: "Palermo, Le Parc Alcorta, biblioteca del living",
  },
  {
    id: "casa-de-verano-pinamar",
    name: "Casa de Verano, Villa de Mar, Pinamar",
    category: "Diseño Interior",
    year: "2020",
    location: "Pinamar, PBA",
    locationFull: "Villa de Mar, Pinamar Norte, Provincia de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Paneles de madera en lamas verticales, piso Patagonia Flooring y mobiliario en hierro negro.",
    memoriaDescriptiva: "Una casa de verano donde la madera clara respira frente al mar. Luz, textura natural y la calma propia de Pinamar.",
    keywords: ["casa de verano Pinamar", "arquitectura costera Buenos Aires", "casas de descanso Villa de Mar"],
    description: "Una casa de verano donde la madera clara respira frente al mar. Luz, textura natural y la calma propia de Pinamar.",
    image: `${WP}/2021/10/2-IMG_1483-1024x682.jpg`,
    gallery: [`${WP}/2021/10/1-estar-correjido.jpg`, `${WP}/2021/10/01aIMG_1866.jpg`, `${WP}/2021/10/2-IMG_1483.jpg`, `${WP}/2021/10/3-IMG_1488.jpg`],
    alt: "Casa de Verano, Villa de Mar, Pinamar",
  },
  {
    id: "puerto-madero-ii-zencity",
    name: "Puerto Madero II, Zencity",
    category: "Diseño Interior",
    year: "2025",
    location: "Puerto Madero, CABA",
    locationFull: "Complejo Zencity, Boulevard J. D. Perón 1400, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina.",
    status: "Obra finalizada",
    services: "Anteproyecto · Proyecto · Dirección de obra · Gestión de compras",
    memoriaTecnica: "Paneles espejados en madera oscura, piso Patagonia Flooring y mesa ratona espejada con detalles en bronce.",
    memoriaDescriptiva: "En Zencity, el espejo y la madera oscura construyen un living de carácter clásico. Puerto Madero con una identidad propia.",
    keywords: ["Complejo Zencity Puerto Madero", "departamento premium Buenos Aires", "torres residenciales CABA"],
    description: "En Zencity, el espejo y la madera oscura construyen un living de carácter clásico. Puerto Madero con una identidad propia.",
    image: `${WP}/2021/08/MAI2863_1.jpg`,
    gallery: [`${WP}/2021/10/MAI2624-copy.jpg`, `${WP}/2021/10/MAI2626.jpg`, `${WP}/2021/10/MAI2630.jpg`, `${WP}/2021/10/MAI2634.jpg`],
    alt: "Puerto Madero II, Zencity, living en complejo Zencity",
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export const categories = ["Todos", "Diseño Interior", "Arquitectura"] as const;
export type Category = (typeof categories)[number];
